### ISSUE TITLE
Categorical and continious data

### ISSUE THREAD

**Issue by arthurPrvst** [JeemyJohn/AnomalyDetection#5]
Hi and thanks for your work !

I have categorical data (that I encoded in one hot vector) and continuous data as well for each data.
The original paper doesn't mention the handling of categorical data.

Does your repo handle it ?

Thanks in advance,

**Comment by JeemyJohn** [comment]
Good question !

And you should known that for categorical feature, different model need different encoding! As for linear model one-hot encoder maybe a good idea. But for trees model, you should not encode  categorical feature into one-hot encoder but for continuous integer, so you can handle your problem.

Get it?

**Comment by JeemyJohn** [comment]
> Hi and thanks for your work !
> 
> I have categorical data (that I encoded in one hot vector) and continuous data as well for each data.
> The original paper doesn't mention the handling of categorical data.
> 
> Does your repo handle it ?
> 
> Thanks in advance,

Good question !

And you should known that for categorical feature, different model need different encoding! As for linear model such as Logistic Regression one-hot encoder maybe a good chosen. But for tree based model, you should not encode categorical feature into one-hot encoder but for continuous integer, so you can handle your problem.

Get it?

**Comment by arthurPrvst** [comment]
Yes I agree (especially that a hot encoder increases the dimension of the problem in my case because of some high cardinality categorical features). According to me, it would be better to encode my categorical features with their frequencies (instead of a simple Integer Encoding). What do you think about it ?

**Comment by JeemyJohn** [comment]
Yes, the two ways to encode categorical feature are essentially equivalent to each other in this algorithm. Which to use, it depends on yourself !
